drop table if exists ingredient cascade;
drop table if exists recipe cascade;
create table ingredient
(
    amount    smallint not null,
    id        bigint generated by default as identity,
    recipe_id bigint,
    name      varchar(255),
    primary key (id)
);
create table recipe
(
    id          bigint generated by default as identity,
    description varchar(255),
    image_path  varchar(255),
    name        varchar(255),
    primary key (id)
);
alter table if exists ingredient
    add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe;


insert into  recipe(description, image_path, name) VALUES
                                                       ('Spaghetti Olive Oil', 'https://www.modernhoney.com/wp-content/uploads/2019/04/Spaghetti-Aglio-e-Olio-2-1200x1295.jpg', 'Spaghetti Olive Oil'),
                                                       ('Spaghetti Bolognese', 'https://staticcookist.akamaized.net/wp-content/uploads/sites/22/2021/06/THUMB-LINK-2020-2-1200x675.jpg', 'Spaghetti Bolognese'),
                                                       ('Beans', 'https://anaffairfromtheheart.com/wp-content/uploads/2015/04/Grandmas-Baked-Beans-4-600x800.jpg', 'Beans');


;

insert into ingredient (amount, recipe_id, name) values (3, 1, 'Spaghetti'),
                                                        (2, 1, 'Garlic'),
                                                        (1, 1, 'Olive Oil'),
                                                        (3, 1, 'Parmiggiano'),
                                                        (3, 2, 'Linguini'),
                                                        (3, 2, 'Bolognese Sauce'),
                                                        (4, 2, 'Tomatoes'),
                                                        (4, 3, 'Beans'),
                                                        (1, 3, 'Salt'),
                                                        (1, 3, 'Bread'),
                                                        (1, 3, 'Peper')
;