drop table if exists users cascade;

create table users
(
    id          bigint generated by default as identity,
    full_name varchar(455),
    email  varchar(255) unique,
    password        varchar(255),
    role        varchar(255),
    primary key (id)
);